// ─── WAF Patterns ─────────────────────────────────────────
// Adapted for Express/Node.js from Wordfence + WP Simple Firewall patterns

export const XSS_PATTERNS: { pattern: RegExp; description: string; score: number }[] = [
  { pattern: /<script[\s>]/i, description: 'Script tag injection', score: 80 },
  { pattern: /<\/script/i, description: 'Script close tag', score: 60 },
  { pattern: /javascript\s*:/i, description: 'JavaScript protocol', score: 70 },
  { pattern: /on\w+\s*=\s*["']/i, description: 'DOM event handler', score: 50 },
  { pattern: /document\.(cookie|domain|write|location)/i, description: 'Document object access', score: 40 },
  { pattern: /eval\s*\(/i, description: 'eval() execution', score: 90 },
  { pattern: /setTimeout\s*\(\s*["']/i, description: 'setTimeout with string', score: 60 },
  { pattern: /setInterval\s*\(\s*["']/i, description: 'setInterval with string', score: 60 },
  { pattern: /Function\s*\(/i, description: 'Function constructor', score: 70 },
  { pattern: /atob\s*\(/i, description: 'Base64 decode function', score: 40 },
  { pattern: /String\.fromCharCode/i, description: 'Char code to string', score: 50 },
  { pattern: /\.innerHTML\s*=/i, description: 'innerHTML assignment', score: 45 },
  { pattern: /\.outerHTML\s*=/i, description: 'outerHTML assignment', score: 45 },
  { pattern: /data\s*:\s*text\/html/i, description: 'Data URI with HTML', score: 55 },
  { pattern: /expression\s*\(/i, description: 'CSS expression', score: 60 },
  { pattern: /-moz-binding\s*:/i, description: 'Mozilla CSS binding', score: 65 },
  { pattern: /behavior\s*:\s*url/i, description: 'IE behavior directive', score: 55 },
  { pattern: /vbscript\s*:/i, description: 'VBScript protocol', score: 80 },
  { pattern: /<iframe[\s>]/i, description: 'Iframe injection', score: 40 },
  { pattern: /<object[\s>]/i, description: 'Object tag injection', score: 35 },
  { pattern: /<embed[\s>]/i, description: 'Embed tag injection', score: 35 },
  { pattern: /<meta[\s>]/i, description: 'Meta tag injection', score: 30 },
  { pattern: /<base[\s>]/i, description: 'Base tag injection', score: 45 },
]

export const SQLI_PATTERNS: { pattern: RegExp; description: string; score: number }[] = [
  { pattern: /union\s+(all\s+)?select/i, description: 'UNION SELECT injection', score: 95 },
  { pattern: /select\s+.+\s+from\s+/i, description: 'SELECT FROM pattern', score: 70 },
  { pattern: /insert\s+into\s+/i, description: 'INSERT INTO injection', score: 90 },
  { pattern: /update\s+.+\s+set\s+/i, description: 'UPDATE SET injection', score: 90 },
  { pattern: /delete\s+from\s+/i, description: 'DELETE FROM injection', score: 95 },
  { pattern: /drop\s+(table|database|index)/i, description: 'DROP command', score: 100 },
  { pattern: /alter\s+table\s+/i, description: 'ALTER TABLE injection', score: 90 },
  { pattern: /create\s+table\s+/i, description: 'CREATE TABLE injection', score: 85 },
  { pattern: /truncate\s+table\s+/i, description: 'TRUNCATE injection', score: 95 },
  { pattern: /exec\s*\(/i, description: 'EXEC execution', score: 85 },
  { pattern: /execute\s*\(/i, description: 'EXECUTE execution', score: 85 },
  { pattern: /xp_cmdshell/i, description: 'SQL Server command shell', score: 100 },
  { pattern: /concat\s*\(/i, description: 'SQL CONCAT function', score: 60 },
  { pattern: /group_concat\s*\(/i, description: 'MySQL GROUP_CONCAT', score: 65 },
  { pattern: /information_schema/i, description: 'Information schema access', score: 80 },
  { pattern: /0x[0-9a-f]{6,}/i, description: 'Hex-encoded SQL', score: 70 },
  { pattern: /char\s*\(\s*\d+/i, description: 'CHAR() SQL encoding', score: 65 },
  { pattern: /having\s+\d+\s*=\s*\d+/i, description: 'HAVING clause injection', score: 55 },
  { pattern: /order\s+by\s+\d+/i, description: 'ORDER BY injection', score: 45 },
  { pattern: /waitfor\s+delay\s/i, description: 'SQL time-based blind', score: 90 },
  { pattern: /benchmark\s*\(/i, description: 'MySQL BENCHMARK', score: 85 },
  { pattern: /sleep\s*\(\s*\d/i, description: 'MySQL SLEEP injection', score: 90 },
  { pattern: /'\s*(or|and)\s+['"]?\d+['"]?\s*=\s*['"]?\d+/i, description: 'Boolean-based SQLi', score: 75 },
  { pattern: /'\s*(or|and)\s+'[^']*'\s*=\s*'/i, description: 'String-based SQLi', score: 75 },
  { pattern: /extractvalue\s*\(/i, description: 'MySQL EXTRACTVALUE', score: 80 },
  { pattern: /updatexml\s*\(/i, description: 'MySQL UPDATEXML', score: 80 },
  { pattern: /load_file\s*\(/i, description: 'MySQL LOAD_FILE', score: 85 },
  { pattern: /into\s+(out|dump)file\s*/i, description: 'INTO OUTFILE/DUMPFILE', score: 100 },
  { pattern: /cast\s*\(/i, description: 'CAST injection', score: 55 },
  { pattern: /convert\s*\(/i, description: 'CONVERT injection', score: 55 },
]

export const DIR_TRAVERSAL_PATTERNS: { pattern: RegExp; description: string; score: number }[] = [
  { pattern: /\.\.\//i, description: 'Directory traversal ../', score: 85 },
  { pattern: /\.\.\\/i, description: 'Directory traversal ..\\', score: 85 },
  { pattern: /\/etc\/passwd/i, description: '/etc/passwd access', score: 100 },
  { pattern: /\/etc\/shadow/i, description: '/etc/shadow access', score: 100 },
  { pattern: /\/proc\/self\/environ/i, description: '/proc/self/environ access', score: 100 },
  { pattern: /\/proc\/self\/status/i, description: '/proc/self/status access', score: 95 },
  { pattern: /\/.htaccess/i, description: '.htaccess access', score: 85 },
  { pattern: /\/\.env/i, description: '.env file access', score: 90 },
  { pattern: /\/\.git/i, description: '.git directory access', score: 95 },
  { pattern: /\/.ssh/i, description: 'SSH directory access', score: 90 },
  { pattern: /\/\.aws/i, description: 'AWS credentials access', score: 95 },
  { pattern: /\/wwwroot/i, description: 'wwwroot access', score: 90 },
  { pattern: /\/windows\/system/i, description: 'Windows system access', score: 90 },
]

export const AGGRESSIVE_PATTERNS: { pattern: RegExp; description: string; score: number }[] = [
  { pattern: /eval\s*\(/i, description: 'eval() execution', score: 100 },
  { pattern: /base64_decode\s*\(/i, description: 'base64_decode()', score: 85 },
  { pattern: /base64_encode\s*\(/i, description: 'base64_encode()', score: 60 },
  { pattern: /gzinflate\s*\(/i, description: 'gzinflate()', score: 80 },
  { pattern: /gzuncompress\s*\(/i, description: 'gzuncompress()', score: 80 },
  { pattern: /str_rot13\s*\(/i, description: 'str_rot13()', score: 70 },
  { pattern: /assert\s*\(/i, description: 'assert() execution', score: 75 },
  { pattern: /create_function\s*\(/i, description: 'create_function()', score: 85 },
  { pattern: /call_user_func/i, description: 'call_user_func()', score: 75 },
  { pattern: /call_user_func_array/i, description: 'call_user_func_array()', score: 75 },
  { pattern: /system\s*\(/i, description: 'system() execution', score: 100 },
  { pattern: /shell_exec\s*\(/i, description: 'shell_exec()', score: 100 },
  { pattern: /passthru\s*\(/i, description: 'passthru()', score: 100 },
  { pattern: /popen\s*\(/i, description: 'popen()', score: 95 },
  { pattern: /proc_open\s*\(/i, description: 'proc_open()', score: 95 },
  { pattern: /pcntl_exec\s*\(/i, description: 'pcntl_exec()', score: 100 },
  { pattern: /exec\s*\(/i, description: 'exec()', score: 95 },
  { pattern: /`\s*[^`]+\`/i, description: 'Backtick execution', score: 90 },
  { pattern: /\$GLOBALS\s*\[/i, description: 'GLOBALS access', score: 80 },
  { pattern: /\$_(GET|POST|REQUEST|COOKIE|SERVER|FILES)\s*\[/i, description: 'Superglobal access', score: 70 },
  { pattern: /fopen\s*\(/i, description: 'fopen() access', score: 60 },
  { pattern: /file_get_contents\s*\(/i, description: 'file_get_contents()', score: 65 },
  { pattern: /file_put_contents\s*\(/i, description: 'file_put_contents()', score: 70 },
  { pattern: /readfile\s*\(/i, description: 'readfile()', score: 60 },
  { pattern: /unlink\s*\(/i, description: 'unlink()', score: 65 },
  { pattern: /rmdir\s*\(/i, description: 'rmdir()', score: 70 },
  { pattern: /curl_exec\s*\(/i, description: 'cURL execution', score: 75 },
  { pattern: /fsockopen\s*\(/i, description: 'Socket open', score: 70 },
  { pattern: /password\s*=\s*["']?\$/i, description: 'Password variable assignment', score: 55 },
  { pattern: /admin\s*=\s*true/i, description: 'Admin flag manipulation', score: 80 },
  { pattern: /is_admin\s*=\s*true/i, description: 'isAdmin flag manipulation', score: 85 },
  { pattern: /role\s*=\s*["']admin["']/i, description: 'Role escalation', score: 90 },
  { pattern: /<\?php/i, description: 'PHP opening tag', score: 70 },
  { pattern: /\x00/i, description: 'Null byte injection', score: 85 },
  { pattern: /\s{49,}/i, description: 'Excessive whitespace', score: 30 },
]

export const WAF_PATTERNS: Record<string, { pattern: RegExp; description: string; score: number }[]> = {
  xss: XSS_PATTERNS,
  sqli: SQLI_PATTERNS,
  dir_traversal: DIR_TRAVERSAL_PATTERNS,
  aggressive: AGGRESSIVE_PATTERNS,
  field_truncation: [
    { pattern: /\x00/, description: 'Null byte', score: 85 },
    { pattern: /\s{49,}/, description: 'Excessive whitespace (49+)', score: 30 },
  ],
}

export const KNOWN_BOT_UA_PATTERNS: { pattern: RegExp; type: 'good' | 'bad' | 'ai' }[] = [
  { pattern: /Googlebot/i, type: 'good' },
  { pattern: /Bingbot/i, type: 'good' },
  { pattern: /Slurp/i, type: 'good' },
  { pattern: /DuckDuckBot/i, type: 'good' },
  { pattern: /Baiduspider/i, type: 'good' },
  { pattern: /YandexBot/i, type: 'good' },
  { pattern: /facebookexternalhit/i, type: 'good' },
  { pattern: /Twitterbot/i, type: 'good' },
  { pattern: /LinkedInBot/i, type: 'good' },
  { pattern: /Slackbot/i, type: 'good' },
  { pattern: /Discordbot/i, type: 'good' },
  { pattern: /TelegramBot/i, type: 'good' },
  { pattern: /WhatsApp/i, type: 'good' },
  { pattern: /Cloudflare-If-Only-Cache/i, type: 'good' },
  { pattern: /CF-IPCountry/i, type: 'good' },
  { pattern: /ChatGPT-User/i, type: 'ai' },
  { pattern: /Claude-Web/i, type: 'ai' },
  { pattern: /ClaudeBot/i, type: 'ai' },
  { pattern: /GPTBot/i, type: 'ai' },
  { pattern: /CCBot/i, type: 'ai' },
  { pattern: /Google-Extended/i, type: 'ai' },
  { pattern: /Bytespider/i, type: 'ai' },
  { pattern: /FacebookBot/i, type: 'ai' },
  { pattern: /Applebot-Extended/i, type: 'ai' },
  { pattern: /anthropic-ai/i, type: 'ai' },
  { pattern: /OAI-SearchBot/i, type: 'ai' },
  { pattern: /sqlmap/i, type: 'bad' },
  { pattern: /nikto/i, type: 'bad' },
  { pattern: /nmap/i, type: 'bad' },
  { pattern: /masscan/i, type: 'bad' },
  { pattern: /zgrab/i, type: 'bad' },
  { pattern: /python-requests/i, type: 'bad' },
  { pattern: /Go-http-client/i, type: 'bad' },
  { pattern: /wget/i, type: 'bad' },
  { pattern: /curl\//i, type: 'bad' },
  { pattern: /scrapy/i, type: 'bad' },
  { pattern: /CensysInspect/i, type: 'bad' },
  { pattern: /PetalBot/i, type: 'bad' },
  { pattern: /AhrefsBot/i, type: 'bad' },
  { pattern: /SemrushBot/i, type: 'bad' },
  { pattern: /MJ12bot/i, type: 'bad' },
  { pattern: /DotBot/i, type: 'bad' },
]

export const KNOWN_CRAWLER_UA_PREFIXES: string[] = [
  'Googlebot', 'Bingbot', 'Slurp', 'DuckDuckBot', 'Baiduspider',
  'YandexBot', 'facebookexternalhit', 'Twitterbot', 'LinkedInBot',
]

export const SUSPICIOUS_PATHS: RegExp[] = [
  /\/wp-admin/i, /\/wp-login/i, /\/wp-config/i, /\/wp-includes/i,
  /\/xmlrpc\.php/i, /\/.env/i, /\/.git\//i, /\/.htaccess/i,
  /\/phpmyadmin/i, /\/adminer/i, /\/mysql/i,
  /\/config\.php/i, /\/database\.yml/i, /\/\.ssh/i,
  /\/backup/i, /\/dump/i, /\/\.sql/i,
  /\/cgi-bin/i, /\/\.bash/i, /\/\.bash_history/i,
  /\/actuator/i, /\/env\.js/i, /\/credentials/i,
]